name: Build Cachix - ARM7
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/cachix.yml'

jobs:
  build-default-image:
    name: Build OS image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux armv7l-linux

      - uses: cachix/cachix-action@v12
        with:
          name: fbleagh
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: |
          sudo apt -y install qemu-user-static

      - name: Build Cachix
        run: |  
           nix-build https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz --option system armv7l-linux --option sandbox false --attr cachix

