name: Delete workflow runs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
# Run on Sunday, at 00:00.

jobs:
  Delete-Workflow-Runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 10
          keep_minimum_runs: 6